name: "KitchenCore"
description: "Gestion de stock alimentaire – Interface mobile avec scanner code-barres"
version: "0.9.32"
slug: "kitchencore"
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "KitchenCore – Interface Web & API"
map:
  - data:rw
panel_icon: mdi:food-apple
panel_title: KitchenCore
